### PR TITLE
Use proto in milvus-proto instead of local

### LINKED ISSUE #330: [Enhancement]: Use milvus-proto lib as protobuf source
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Use milvus-proto lib as protobuf source

### Why is this needed?

For consistency between sdk repo and milvus main repo.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by xiaocai2333**
Resolves #330

Signed-off-by: cai.zhang <cai.zhang@zilliz.com>

### CODE REVIEW

**Comment by congqixia** [comment]
@xiaocai2333 overall lgtm
there is one concern here. Change of field name to index name in index related API might cause confusion for 2.2 users. Could we keep the original APIs, marking them deprecated and add new index name ones?

**Comment by xiaocai2333** [comment]
> @xiaocai2333 overall lgtm there is one concern here. Change of field name to index name in index related API might cause confusion for 2.2 users. Could we keep the original APIs, marking them deprecated and add new index name ones?

I think it's a good idea, and should we keep indexName and fieldName for later expansion? @congqixia @czs007

**Review by congqixia — APPROVED** [review]
/lgtm

**Pull request merged**
