### PR TITLE
modify the description

### PR DESCRIPTION
**Pull request by jhonroxton**
chang code:
`Description:    "this is the example collection for inser and search"`
to:
`Description:    "this is the example collection for insert and search"`

### CODE REVIEW

**Comment by congqixia** [comment]
@jhonroxton thanks for the contribution, could you please fix the DCo issue?

**Comment by jhonroxton** [comment]
> @jhonroxton thanks for the contribution, could you please fix the DCo issue?

@congqixia ok

**Comment by jhonroxton** [comment]
> /approve

**Review by congqixia — APPROVED** [review]
/kind improvement
/lgtm

**Pull request merged**
