### PR TITLE
flush segment before create index

### LINKED ISSUE #277: Call flush() in the grpcClient.CreateIndex()
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Keep consistence with pymilvus. In the create_index() firstly call the flush().

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Environment

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by wg1026688210**
flush segment before create index
fix #277
Signed-off-by: wgcn <1026688210@qq.com>

### CODE REVIEW

**Review by letian-jiang — APPROVED** [review]
/lgtm

**Comment by letian-jiang** [comment]
@wg1026688210 This repo requires a GPG sign. Please add it to verify your commit. 
FYI: https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification

**Review by congqixia — APPROVED** [review]
/lgtm

**Comment by wg1026688210** [comment]
@letian-jiang cc

**Comment by wg1026688210** [comment]
> @wg1026688210 This repo requires a GPG sign. Please add it to verify your commit. FYI: https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification

I rebase the commit , `LGTM TAG` is needed, PTAL @letian-jiang

**Pull request merged**
