### PR TITLE
tls example

### PR DESCRIPTION
**Pull request by xiyichan**
https://github.com/milvus-io/milvus/issues/16459
Signed-off-by: xiyichan <2863768433@qq.com>

### CODE REVIEW

**Comment by congqixia** [comment]
@xiyichan nice example for TLS connection example. Looks like this pr need to squash into one commit. Please follow the rules to add a issue or mark this PR kind/improvement.
BTW, shall we mark the version of Milvus & Milvus SDK version to support TLS?

**Comment by xiyichan** [comment]
> @xiyichan nice example for TLS connection example. Looks like this pr need to squash into one commit. Please follow the rules to add a issue or mark this PR kind/improvement. BTW, shall we mark the version of Milvus & Milvus SDK version to support TLS?

https://github.com/milvus-io/milvus/issues/16459 this is milvus issue which support tls. 
https://github.com/milvus-io/milvus/pull/16706 this pr for milvus support tls.

**Comment by congqixia** [comment]
@xiyichan github setting need commit to be signed. Could you please fix that?

**Comment by xiyichan** [comment]
> @xiyichan github setting need commit to be signed. Could you please fix that?

I don't know how to fix. Can you guide me how to fix this?

**Comment by letian-jiang** [comment]
> > @xiyichan github setting need commit to be signed. Could you please fix that?
> 
> I don't know how to fix. Can you guide me how to fix this?

Thanks for your contribution. All your need is to execute `git commit -s --amend` in your local repository.

FYI: https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

**Comment by xiyichan** [comment]
> > > @xiyichan github setting need commit to be signed. Could you please fix that?
> > 
> > 
> > I don't know how to fix. Can you guide me how to fix this?
> 
> Thanks for your contribution. All your need is to execute `git commit -s --amend` in your local repository.
> 
> FYI: https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

done

**Review by congqixia — APPROVED** [review]
/lgtm

**Comment by congqixia** [comment]
manually add `ci-passed` label for example code change

**Pull request merged**
