### PR TITLE
feat: Add Github Issue Forms

### LINKED ISSUE #202: Add GitHub Issue Forms
## Title
GitHub has recently rolled out a [public beta for their issue forms](https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/) feature. This would allow you to create interactive issue templates and validate them 🤯.

## Description
As we can see this repository currently uses no issue template. Your task is to create GitHub issue forms for this repository. We can use standard issue templates as a reference for this PR.

### PR DESCRIPTION
**Pull request by Hard-Coder05**
closes #202

### CODE REVIEW

**Comment by Hard-Coder05** [comment]
> Hi @Hard-Coder05. Thank you for you pr adding Issue forms! Much appreciated. Minor change about this project name is needed. And the DCO check failed, could you please fix that?

@congqixia I have fixed the DCO check!

**Comment by Hard-Coder05** [comment]
@congqixia When will this PR get merged? I guess its ready!

**Comment by congqixia** [comment]
> @congqixia When will this PR get merged? I guess its ready!

Yeap. All checks and content are fine. Could you please squash your commits into one? It's the unified standard for Milvus repos.

**Pull request merged**
