### PR TITLE
enhance: Add Describe User methods

### PR DESCRIPTION
**Pull request by punkerpunker**
resolves: #698

I've added an entity:

```
type UserDescription struct {
	Name  string
	Roles []string
}
```

And two methods and tests for them:

- `DescribeUser(ctx context.Context, username string) (entity.UserDescription, error)` - which returns UserDescription for a specific user.
- `DescribeUsers(ctx context.Context) ([]entity.UserDescription, error)` - which returns UserDescription for all users presented. 

The thing that I want to raise is that I am not sure if it is feasible to return empty `UserDescription` entity in case the user from `DescribeUser` method doesn't exist, I would highly appreciate suggestions here.

Also, I am not much familiar with the `milvus-sdk-go` codebase and this is my first PR here, so any comments/feedback/suggestions would be highly appreciated, thanks!

### CODE REVIEW

**Comment by punkerpunker** [comment]
Failing tests doesn't seem to be related to this specific change btw

**Comment by congqixia** [comment]
@punkerpunker thanks for the contribution. I've fixed failing cases. could you please rebase and fix the lint issue reported in `lint` action?

**Comment by punkerpunker** [comment]
@congqixia seems like fixed

**Comment by punkerpunker** [comment]
Thanks @congqixia, once again the tests falling doesn't seem to be related to the change :)

**Comment by punkerpunker** [comment]
Hey @congqixia, are we concerned about something in particular so we don't merge this one yet? Want to start working on tf-provider, and that piece is missing :)

**Comment by congqixia** [comment]
@punkerpunker sorry for the late reply. Master branch e2e cases was unstable due to rapid change of milvus master behavior. We have just fixed the cases. You can rebase your PR now

**Review by congqixia — APPROVED** [review]
/lgtm

**Pull request merged**
