### PR TITLE
Problem handlingpanic: runtime error: slice bounds out of range

### LINKED ISSUE #231: [Bug]: panic: runtime error: slice bounds out of range
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Exceptions occur when searching multiple sets of vectors "panic: runtime error: slice bounds out of range "

### Expected Behavior

1、
```
func main() {
	// Milvus instance proxy address, may verify in your env/settings
	milvusAddr := `xxxxxxxxxxxx`

	// setup context for client creation, use 2 seconds here
	ctx := context.Background()
	ctx, cancel := context.WithTimeout(ctx, 5*time.Second)
	defer cancel()

	c, err := client.NewGrpcClient(ctx, milvusAddr)

	vector1 := entity.FloatVector([]float32{1,2,3,4,5,6,7,8})
	vector2 := entity.FloatVector([]float32{1.1,1.2,1.3,1.4,1.5,1.6,1.7,1.8})
	vector3 := entity.FloatVector([]float32{2.1,2.2,2.3,2.4,2.5,2.6,2.7,2.8})
	vector4 := entity.FloatVector([]float32{3.1,3.2,3.3,3.4,3.5,3.6,3.7,3.8})
	entitys := []entity.Vector{vector1,vector2,vector3,vector4}

	sp, _ := entity.NewIndexFlatSearchParam(50)
	sr, err := c.Search(ctx, "gosdk_insert_example", []string{}, "Year > 1990", []string{"ID"}, entitys, "Vector",
		entity.L2, 10, sp)
	fmt.Println(sr)
	if err != nil {
		log.Fatal("fail to search collection:", err.Error())
	}
}
```

2、
image

### Steps To Reproduce

_No response_

### Environment

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by suibianmzl**
Fix #231 

Problem repair handling "panic: runtime error: slice bounds out of range"

### CODE REVIEW

**Comment by congqixia** [comment]
@suibianmzl thanks for this PR! 
But the commit DCO failed.
Please rebase master and fix DCO issue.
If you don't has a moment, you could provided an email of your github account so that add your as a co-author.
Thanks in advance.

**Comment by suibianmzl** [comment]
Hello! 276212324@qq.com This is the email address of my GitHub account

**Comment by congqixia** [comment]
Fixed in #249. Listed you as a co-author. Closing this PR

**Pull request closed without merging**
