### PR TITLE
Remove duplicate checks

### PR DESCRIPTION
**Pull request by xiaocai2333**
Signed-off-by: Cai.Zhang <cai.zhang@zilliz.com>

### CODE REVIEW

**Comment by congqixia** [comment]
@xiaocai2333 this problem shall be related to issue #265. Removing the request validation is a doable workaround but not recommended.

**Comment by xiaocai2333** [comment]
I just want to remove duplicate checks for requests, so it's nothing to do with #265.

**Review by congqixia — APPROVED** [review]
/lgtm

**Pull request merged**
